---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trow
  namespace: trow
spec:
  interval: 5m
  chart:
    spec:
      chart: trow
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: trow
        namespace: trow
      interval: 10m
  values:
    image:
      pullPolicy: IfNotPresent
    trow:
      domain: trow.jaackdreality.com
      validation:
        enabled: false
      imagePullSecrets:
    service:
      type: NodePort
      port: 8000
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: trow.jaackdreality.com
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-staging
      hosts:
        - paths: ['/']
          host:
      tls:
        - hosts:
          - trow.jaackdreality.com
          secretName: trow-tls-secret-staging