---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: trow
  namespace: trow
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/22ndtech/trow.git
