# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: trow-staging
#   namespace: trow
# spec:
#   secretName: trow-tls-secret
#   dnsNames:
#   - trow.jaackdreality.com
#   issuerRef:
#     name: letsencrypt
#     kind: ClusterIssuer
#     group: cert-manager.io
#   isCA: true
#   commonName: trow.jaackdreality.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trow
  namespace: trow
spec:
  secretName: trow-tls-secret-staging
  dnsNames:
  - trow.jaackdreality.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
  isCA: true
  commonName: trow.jaackdreality.com  