---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trow
  namespace: trow
spec:
  secretName: letsencrypt
  dnsNames:
  - trow.jaackdreality.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  isCA: true
  commonName: trow.jaackdreality.com