---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tekton
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/tekton-pipeline
      version: 0.0.1
      sourceRef:
        kind: GitRepository
        name: tekton-helm-chart
        namespace: flux-system
      interval: 1m
  values:
    auth:
      docker:
        url: https://hub.docker.com
