---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jaackd-ca
  namespace: jaackd
spec:
  secretName: letsencrypt
  dnsNames:
  - jaackd.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  isCA: true
  commonName: jaackd.com