---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jaackd-ca-staging
  namespace: jaackd
spec:
  secretName: letsencrypt-staging
  dnsNames:
  - jaackd.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
  isCA: true
  commonName: jaackd.com