---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: mongo-kubernetes-operator
  namespace: mongo
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/22ndtech/mongodb-kubernetes-operator