apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: port-forward
  namespace: mongo
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", pods/portforward]
  verbs: ["get", "list", "create"]