---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 3.15.2
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress-controller
        namespace: flux-system
      interval: 10m
  values:
    admissionWebhooks:
      failurePolicy: Ignore