---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ndtech-code-server
  namespace: ndtech-code-server
spec:
  interval: 5m
  chart:
    spec:
      chart: ./chart/ndtech-code-server
      sourceRef:
        kind: GitRepository
        name: ndtech-code-server
        namespace: flux-system
      interval: 1m
  values:
    extraSecretMounts:
      - name: kube-config-admin
        mountPath: /home/coder/.kube
        secretName: code-server-secret-files
        readOnly: true