---
apiVersion: v1
kind: Namespace
metadata:
  name: john
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: john-resource-quota
  namespace: john
spec:
  hard:
    limits.cpu: "4000m"
    limits.memory: 8Gi
    requests.cpu: "2000m"
    requests.memory: 4Gi