---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ndtech-node-api
  namespace: ndtech
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/22ndtech/ndtech-node-api

