---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jaackd-reality-ca-staging
  namespace: ndtech
spec:
  secretName: letsencrypt-staging
  dnsNames:
  - jaackdreality.com
  - www.jaackdreality.com
  - tekton.jaackdreality.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
  isCA: true
  commonName: jaackdreality.com