---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-22ndtech-ca
  namespace: ndtech
spec:
  secretName: letsencrypt-www-22ndtech
  dnsNames:
  - www.22ndtech.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  isCA: true
  privateKey:
    rotationPolicy: Always