---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-volume-provisioner
  namespace: nfs-volume-provisioner
spec:
  releaseName: nfs-volume-provisioner
  targetNamespace: nfs-volume-provisioner
  interval: 5m
  chart:
    spec:
      chart: ./charts/nfs-volume-provisioner
      version: 0.0.1
      sourceRef:
        kind: GitRepository
        name: nfs-volume-provisioner
        namespace: nfs-volume-provisioner
      interval: 1m