---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: nfs-volume-provisioner
  namespace: nfs-volume-provisioner
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/22ndtech/nfs-volue-provisioner
