---
apiVersion: v1
kind: Namespace
metadata:
  name: kimhegedus
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: kimhegedus-resource-quota
  namespace: kimhegedus
spec:
  hard:
    limits.cpu: "1000m"
    limits.memory: 2Gi
    requests.cpu: "2000m"
    requests.memory: 4Gi