---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/jetstack/cert-manager