# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: cert-manager
#   namespace: cert-manager
# spec:
#   interval: 5m
#   chart:
#     spec:
#       chart: ./deploy/charts/cert-manager
#       version: 0.0.1.5
#       sourceRef:
#         kind: GitRepository
#         name: cert-manager
#         namespace: flux-system
#       interval: 1m
#   values:
#     installCRDs: true
#     image:
#       tag: v1.1.0
#     webhook:
#       image:
#         tag: v1.1.0
#     cainjector:
#       image:
#         tag: v1.1.0
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.1.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 10m
  values:
    installCRDs: true
  #   admissionWebhooks:
  #     failurePolicy: Ignore